### PR TITLE
added explicit referred TB processing

### PR DESCRIPTION
**Pull request by equalsJeffH**
This PR mostly just adds explicit processing rules for referred Token Bindings. It also denotes client processing rules, server processing rules, and moves the admonition regarding extensions into server processing rules. 

HTH,

=JeffH

### CODE REVIEW

**Comment by Andrei-Popov** [comment]
I feel that the detailed discussion of the various TB types and their interaction belongs in the HTTPSTB (and potentially, other documents that describe the use of TB with various application protocols).  My thinking is that multiple federation schemes exist (even within the HTTP protocol alone), so hard-coding this in TBPROTO may limit future use of the TB protocol.

**Comment by equalsJeffH** [comment]
Ok, so I will close this PR, however, various portions of the editorial revisions remain salient -- I'll create another PR based on them.

**Comment by equalsJeffH** [comment]
re-opening, see issue #21 -- have added commits to update these proposed changes.

**Comment by equalsJeffH** [comment]
NOTE: The present proposed content of PR#16 does not quite fully accomplish the separation of processing rules from the TBMsg syntax exposition, nor clarify the semantics of referred bindings, to the extent that I/we intend to -- tho, if this overall direction seems ok, the necessary further editing can be done either before or after merge of this PR.

**Pull request merged**
