### PR TITLE
TBPROTO: update ECPoint.point to be in X9.62 format with…

### LINKED ISSUE #62: TBPROTO: Not using uncompressed point from X9.62
The encoding of `ECPoint.point` in the spec varies from the definition in X9.62 unnecessarily.  The uncompressed point form is used by numerous specs.  The only cost to having this consistency is an extra octet (0x04).  For that low, low price, you can reference other specs rather than having to define the point encoding format yourself.

### PR DESCRIPTION
**Pull request by equalsJeffH**
… leading 0x04 byte, fixes #62

### CODE REVIEW

**Comment by b---c** [comment]
As said in #62 I'd prefer to leave the EC point format as it's currently defined in the draft. I don't see the value of using the X9.62 format with the extra 0x04 byte - especially at this late stage in the process.

**Comment by Andrei-Popov** [comment]
IMHO we should not drag the 0x04 nonsense into new protocols, such as Token Binding. I'm not aware of any good technical reason to make this change.

**Comment by nharper** [comment]
(Mainly repeating what I said in #62.) I don't see a good reason why we're defining our own EC point format instead of using an existing one (saving a single byte isn't a good reason). If there's another spec that defines EC points similar to the TB definition, I'd be fine referring to that instead of X9.62.

**Comment by equalsJeffH** [comment]
seems to me @nharper has a good point.

**Comment by Andrei-Popov** [comment]
I'm not proposing that we save a byte. Instead, I am suggesting that we don't add unused bytes with arbitrary values to the protocol. An ANSI spec defines this byte to distinguish one option from other options. In TB, for ecdsap256, we don't have multiple options, and therefore don't need the 0x04 byte.

In any case, this will probably have to get decided on the mailing list.

**Comment by waywardgeek** [comment]
Changing the EC-P256 key format to an old X9.62 standard while leaving the RSA in a custom format does not make sense to me.  It also does not make sense to me to use X9.62 for EC points, while using ASN.1 for RSA keys (but not signatures) like we do in most crypto libraries like the one from OpenSSL.

EC users have it easy: Simply strip off the leading 0x4.  Regardless of the delay this PR would cause, I think it would make the spec worse, not better.

**Comment by equalsJeffH** [comment]
as noted in https://www.ietf.org/mail-archive/web/unbearable/current/msg01033.html (I wrote on 7-Dec-2016):
>  Seems to me that given the input from several implementors that they are parsing/constructing the ECC public key "by hand" in any case that we ought to leave well enough alone and close this PR#82.

..and no one has disagreed with it, so am closing this PR.

**Pull request closed without merging**
