### PR TITLE
Remove requirement to terminate connections

### PR DESCRIPTION
**Pull request by martinthomson**
And instead insist on rejecting the message instead.

### CODE REVIEW

**Comment by PiotrSikora** [comment]
+1

However, I disagree with your choice regarding the status code.

Per [RFC7235, sec. 3.1. 401 Unauthorized](https://tools.ietf.org/html/rfc7235#section-3.1):

```
The 401 (Unauthorized) status code indicates that the request has not
been applied because it lacks valid authentication credentials for
the target resource.  The server generating a 401 response MUST send
a WWW-Authenticate header field (Section 4.1) containing at least one
challenge applicable to the target resource.
```

There is no way response to broken Token Binding should have `WWW-Authenticate` header.

I suggest use of the generic `400 Bad Request` status code instead, since this is indeed a bad request.

Per [RFC7231, sec. 6.5.1. 400 Bad Request](https://tools.ietf.org/html/rfc7231#section-6.5.1):

```
The 400 (Bad Request) status code indicates that the server cannot or
will not process the request due to something that is perceived to be
a client error (e.g., malformed request syntax, invalid request
message framing, or deceptive request routing).
```

Coincidentally, this is also the status code I'm using in the [NGINX module for Token Binding](https://github.com/google/ngx_token_binding).

Also, `MUST` or `SHOULD` would be better than `might be`, but that might be wrong document to include this requirement.

**Comment by siyengar** [comment]
+1.

The status code probably also needs to be in the tokbind HTTP draft as well.

**Comment by b---c** [comment]
Agree that 401 isn't right. 400 works but what about 403? I'm honestly not sure so asking. 

And yes, the status code definitely needs to be in the HTTPSTB draft as well. And that's where the normative `MUST` or `SHOULD` would go.

**Comment by PiotrSikora** [comment]
I think that 400 is more suitable than 403.

The way I see it is that this is misbehaving client sending invalid requests. It has nothing to do with application-level credentials, IMHO.

**Comment by martinthomson** [comment]
OK, 400 it is.

**Comment by Andrei-Popov** [comment]
Addressed in TBPROTO-11 and HTTPSTB-7

**Pull request closed without merging**
